server {
    listen 8080;
    root www;
    server_name localhost;
    location / { methods GET; root www; index index.html; }
    location /cgi-bin {
        methods GET POST;
        root www;
        cgi_handler .py /usr/bin/python3;
    }
}
server {
    listen 8081;
    root www2;
    server_name localhost;
    location / { methods GET; root www2; index index.html; }
}

