server {
    listen 8080;
    root www;
    server_name localhost;
    client_max_body_size 100000000;

    location / {
        methods GET;
        root www;
        index index.html;
    }

    location /directory {
        methods GET POST;
        root www;
        index youpi.bad_extension;
        cgi_handler .bla ./cgi_tester;
    }
    
    location /post_body {
        methods POST;
        upload_store www/post_body;
        client_max_body_size 100;
        root www;
    }

    location /cgi-bin {
        methods GET POST;
        root www;
        cgi_handler .php /usr/bin/php-cgi;
        cgi_handler .py /usr/bin/python3;
    }
}

