# TEST: deux serveurs sur ports differents
server
{
    listen      8080;
    server_name site1.local;
    root        www;
    location /
    {
        methods GET POST;
        index   index.html;
    }
}

server
{
    listen      4242;
    server_name site2.local;
    root        www/test;
    location /
    {
        methods GET;
        index   another.html;
    }
}
