# TEST: redirections 301 et 302
server
{
    listen      8080;
    server_name redirect.local;
    root        www;

    location /
    {
        methods GET;
        index   index.html;
    }

    location /old-page
    {
        return 301 /new-page;
    }

    location /moved
    {
        return 302 /destination;
    }
}
