# TEST: config complete avec toutes les directives
server
{
    listen                  9090;
    server_name             full.local;
    root                    www;
    index                   index.html;
    client_max_body_size    5M;

    error_page 404 /error/404.html;
    error_page 500 /error/500.html;

    location /
    {
        methods     GET POST;
        index       index.html;
        autoindex   off;
    }

    location /upload
    {
        methods                 GET POST DELETE;
        upload_store            www/upload;
        client_max_body_size    50M;
    }

    location /old
    {
        return 301 /new;
    }

    location /cgi-bin
    {
        root        www/cgi-bin;
        methods     GET POST;
        cgi_handler .py  /usr/bin/python3;
        cgi_handler .sh  /bin/bash;
    }

    location /files
    {
        root        www/files;
        methods     GET;
        autoindex   on;
    }
}
