# =============================================================================
# webserv_3sites.conf — 3 server configuration
# =============================================================================
#
# SETUP:
#   ./webserv webserv_3sites.conf
#
# SERVERS:
#   Site 1 — port 8080 — full featured (CGI, uploads, readonly, error pages)
#   Site 2 — port 8081 — CGI cookies
#   Site 3 — port 8082 — CGI cookies
# =============================================================================


# ─────────────────────────────────────────────────────────────────────────────
# SERVER 1 — port 8080
# ─────────────────────────────────────────────────────────────────────────────
server {
    listen                  127.0.0.1:8080;
    server_name             localhost;
    root                    www/site1;
    index                   index.html;
    error_page              404 /errors/404.html;
    client_max_body_size    200;

    location / {
        root            www/site1;
        index           index.html;
        methods         GET POST;
        upload_store    www/site1/uploads;
    }

    location /uploads {
        root            www/site1;
        methods         GET POST DELETE;
        upload_store    www/site1/uploads;
    }

    location /readonly {
        root            www/site1;
        methods         GET;
    }

    location /errors {
        root            www/site1;
        methods         GET;
    }

    location /redirect {
        return 301 http://127.0.0.1:8080/;
    }

    location /cookie {
        return 302 /cookie/cookie.py;
    }

    location /cookie/cookie.py {
        root            www;
        methods         GET POST;
        cgi_handler     .py /usr/bin/python3;
    }

    location /login {
        return 302 /login/login.py;
    }

    location /login/login.py {
        root            www;
        methods         GET POST;
        cgi_handler     .py /usr/bin/python3;
    }

    location /login/logout.py {
        root            www;
        methods         GET POST;
        cgi_handler     .py /usr/bin/python3;
    }

    location /cgi-bin {
        root            www/site1;
        methods         GET POST;
        cgi_handler     .py  /usr/bin/python3;
        cgi_handler     .php /usr/bin/php-cgi;
        cgi_handler     .pl  /usr/bin/perl;
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# SERVER 2 — port 8081
# ─────────────────────────────────────────────────────────────────────────────
server {
    listen                  127.0.0.1:8081;
    server_name             localhost2;
    root                    www/site2;
    index                   index.html;
    error_page              404 /404.html;

    location / {
        root            www/site2;
        index           index.html;
        methods         GET;
    }

    location /cgi-bin {
        root            www/site2;
        methods         GET POST;
        cgi_handler     .py /usr/bin/python3;
    }
}


# ─────────────────────────────────────────────────────────────────────────────
# SERVER 3 — port 8082
# ─────────────────────────────────────────────────────────────────────────────
server {
    listen                  127.0.0.1:8082;
    server_name             localhost3;
    root                    www/site3;
    index                   index.html;

    location / {
        root            www/site3;
        index           index.html;
        methods         GET;
    }

    location /cgi-bin {
        root            www/site3;
        methods         GET POST;
        cgi_handler     .py /usr/bin/python3;
    }
}

